---
title: "ETL template"
output: html_notebook
---


# R approach

Descargar datos de [este link](https://drive.google.com/drive/folders/1wzyn9IYyV6gvXrvYFraTxPJQxk1exVTx?usp=sharing) previa petición de autorización.

```{r message=FALSE, warning=FALSE}
# library(readxl)
# Archivo origen 
# http://sociedadcivil.ministeriodesarrollosocial.gob.cl/wp-content/uploads/2021/03/Donaciones_2019.xlsx
# data <- read_excel("~/Downloads/Donaciones_2019.xlsx", 
    # col_types = c("numeric", "date", "text", 
    #     "text", "text", "numeric", "numeric", 
    #     "numeric"))
# save(data,file="data_local/Donaciones2019.RData")
load("../data_local/Donaciones2019.RData")
Proyecto <- data.frame(id=1:length(levels(as.factor(data$`NOMBRE DEL PROYECTO`))),
                       nombre=levels(as.factor(data$`NOMBRE DEL PROYECTO`)))
Donatarios <- data.frame(id=1:length(levels(as.factor(data$DONATARIO))),
                         nombre=levels(as.factor(data$DONATARIO)))
Donantes <- data.frame(id=1:length(levels(as.factor(data$DONANTE))),
                         nombre=levels(as.factor(data$DONANTE)))
```


# Análisis exploratorio

```{r}
# nrow(data %>% filter(`DONATARIO`=="Fundación Jóvenes por una América Solidaria (América Solidaria)") %>% select(`NOMBRE DEL PROYECTO`))
# data$DONATARIO <- as.character(data$DONATARIO)
# proyectos <- unique(data %>% filter(`DONATARIO`=="Fundación Jóvenes por una América Solidaria (América Solidaria)") %>% select(`NOMBRE DEL PROYECTO`))
df <- data.frame(monto=c(1,2,3,4),proyecto=c("a","a","b","b"),donatario=c("x","x","x","x"),fecha=c(1,2,1,2),donante=c("j","k","l","n"),donaa=c(1,1,0,0),donab=c(0,0,1,1))
df
```

## Modelos

$$monto_i=\alpha+\beta_1\cdot Trimestre_i+\beta_2\cdot PersonaJurídica_i+\begin{cases} \overbrace{\beta_3\cdot Trabajadores_i+\beta_4\cdot TramoVentas_i}^{\text{sólo Personas Jurídicas}}\\...\\\underbrace{\beta_5\cdot Genero_i+\beta_6\cdot GSE_i}_{\text{sólo Personas Naturales}}\end{cases}+...+\epsilon_i$$
### Variable dependiente limitada

$$\underbrace{Prob(\text{Dona a a})}_{donaa}=F(\alpha+\beta\cdot donante_i+\epsilon_i>0)$$

$$\underbrace{Prob(\text{Dona a b})}_{donab}=F(\alpha+\beta\cdot donante_i+\epsilon_i>0)$$

## Cruzar información

Enriquecer datos con:

- SII

```{r}
# Descargamos datos del SII
# 143.7 MB
# download.file("https://www.sii.cl//estadisticas/nominas/PUB_Empresas_AT2015_AT2019_202101.xlsb", destfile = "PUB_Empresas_AT2015_AT2019_202101.xlsb")
# Los datos están en un amigable formato xlsb que se puede leer en R con la librería readxlsb
# Se debe instalar inicialmente si no está instalada
# install.packages("readxlsb")
# library(readxlsb)
# OJO que esto Cuelga el computador
# df = read_xlsb("../data_local/PUB_Empresas_AT2015_AT2019_202101.xlsb", sheet="AC_2018", debug = TRUE)
# library(readr)
# dataSII <- read_delim("../data_local/PUB_Empresas_AT2015_AT2019_202101.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
# save(dataSII,file="dataSII.RData")
load("../data_local/dataSII.RData")
```

- Registro Ley 19862

[Ejemplo de ficha de organización](https://www.registros19862.cl/fichas/ver/rut/65032490/clase/5)


# Python approach via reticulate

Instalar Anaconda previamente. Sino, para configurar Python, seguir [este tutorial](https://support.rstudio.com/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio).

```{r}
# knitr::knit_engines$set(python = reticulate::eng_python)
library(reticulate)
# Use specific python
# use_python("/home/scea/anaconda3/bin/python")
# Check python config
# py_config()
# Command line python
# repl_python()
# Verify conda environments
# conda_list()
# indicate that we want to use a specific condaenv
# use_condaenv("r-reticulate")
# Install package in default conda environment "r-reticulate"
# py_install("pandas")
# py_install("time")
# py_install("matplotlib")
# Install package in specific environment "environment-name"
# virtualenv_install("environment-name", "scipy")
# Problem: 
# QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-sebastian'
# No protocol specified
# qt.qpa.screen: QXcbConnection: Could not connect to display :0
# Could not connect to any X display.
# Solution found on https://community.rstudio.com/t/how-to-display-the-plot-in-the-python-chunk/22039/2
matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```


```{python}
data=r.data.head()

```


